# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LaunchTuiMacos < Formula
  desc "TUI to manage macOS LaunchAgents and LaunchDaemons"
  homepage "https://github.com/jeremiealcaraz/launch-tui-macos"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/JeremieAlcaraz/launch-tui-macos/releases/download/v0.1.3/launch-tui-macos_0.1.3_darwin_amd64.tar.gz"
    sha256 "58a8b125c1fbd7285827332b0bcc53eefdef7a9d32efcc61b4702716bdc3dad6"

    define_method(:install) do
      bin.install "launch-tui-macos"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/JeremieAlcaraz/launch-tui-macos/releases/download/v0.1.3/launch-tui-macos_0.1.3_darwin_arm64.tar.gz"
    sha256 "3e810907421a46307d0d76b1e24242a75c4226d2e8960ad177b4c5763d06a8d5"

    define_method(:install) do
      bin.install "launch-tui-macos"
    end
  end
end
