# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "Notion CLI for humans and AI agents — optimized token consumption."
  homepage "https://github.com/JeremieAlcaraz/notion-cli"
  version "0.1.0"
  license "MIT"

  depends_on "gum" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.1.0/notion-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5a24454601ea862cbcc146cbcba71ecdfe89929bef601d2e7aaf3bd33497c347"

      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.1.0/notion-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "ba6a7b6373c93f4bf2e673057baf10ebd5eb5fa6a2328563aabf9cda1124130a"

      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.1.0/notion-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "28e391655742bce2e6ce989b0901698757bb00188ed71deabeef364e50c9af58"
      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.1.0/notion-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "119ab0afec58d4aada6102e58aa36b53c518a224e9d2878bea25507328c2bd76"
      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  def post_install
    ohai "Install the AI agent skill:"
    ohai "  notion skill install"
  end
end
