# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "Notion CLI for humans and AI agents — optimized token consumption."
  homepage "https://github.com/JeremieAlcaraz/notion-cli"
  version "0.2.0"
  license "MIT"

  depends_on "gum" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.2.0/notion-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "24f09f021179df525e5a6208b69c4891a4da3da1ae1f3b12ea6bef63a429321b"

      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.2.0/notion-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "26d1ddbb93a78693c760d67bbc75deea19e4d0dc1a871bec195181314a452b3a"

      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.2.0/notion-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "5b5ffc12b706b53acd6fdc8dea34dd73e278c9bb2fcd51b50b95eee2b6042ce1"
      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JeremieAlcaraz/notion-cli/releases/download/v0.2.0/notion-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "8baeaf8c54723503e170fa9919301a31ccd3ae65c1b0c6b2a8fe4f22df6f6f5a"
      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  def post_install
    ohai "Install the AI agent skill:"
    ohai "  notion skill install"
  end
end
