# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unq < Formula
  desc "Tiny macOS CLI to remove com.apple.quarantine"
  homepage "https://github.com/JeremieAlcaraz/unq"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/JeremieAlcaraz/unq/releases/download/v0.1.0/unq_0.1.0_darwin_amd64.tar.gz"
    sha256 "6411f7af609e37a1dc0ca2cc938003a6bb072ae177948ed0ea0326b7de3a3130"

    define_method(:install) do
      bin.install "unq"
    end
  end

  if Hardware::CPU.arm?
    url "https://github.com/JeremieAlcaraz/unq/releases/download/v0.1.0/unq_0.1.0_darwin_arm64.tar.gz"
    sha256 "ec6e70e76e0bc094999c204e3b126ca8fa25bf7eab003da0cbf68be8309ff973"

    define_method(:install) do
      bin.install "unq"
    end
  end
end
